version: "3.9"
services:
  api:
    build: .
#    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0'
    volumes:
      - ".:/code"
    ports:
      - 8000:8000
    depends_on:
      - mongo-local
    container_name: API-KASINVOICE
    command: uvicorn app:app --host 0.0.0.0 --reload

  mongo-local:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: kasinvoice-user
      MONGO_INITDB_ROOT_PASSWORD: kasinvoice-password

    volumes:
      - mongo-data:/data/db

volumes:
 mongo-data:
